services:
  php:
    build: ./docker/php
    container_name: only-php
    restart: always
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: only-nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - php
    networks:
      - app-network


  db:
    build: ./docker/mysql
    container_name: only-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: only-phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db_data:


networks:
  app-network:
    driver: bridge